# -*- coding: utf-8 -*-
"""
/***************************************************************************
 aa
                                 A QGIS plugin
 aa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-09
        copyright            : (C) 2025 by aa
        email                : aa
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'aa'
__date__ = '2025-05-09'
__copyright__ = '(C) 2025 by aa'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load aa class from file aa.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aa import aaPlugin
    return aaPlugin()
